[package]
name = "tare"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.24.0"  # For vector math (Vec2 and Vec3)
dashi = {git = "https://github.com/JordanHendl/dashi"}
bento = {path = "../bento"}

[dev-dependencies]
winit = { version = "0.26" }

